[tests]
min_version = "v0.11.0"

[tests.steps]
install = [
    "apt update",
    "apt install nodejs npm",
]

[tests.import]
command = "make -j2 dev"

[tests.ports]
"8000/tcp" = ""
"3000/tcp" = ""

[services.redis]
image = "redis:latest"

[services.redis.ports]
"6379/tcp" = ""

[services.redis.export]
REDIS_URL = "redis://{HOST}:{PORT;6379/tcp}"

[services.database]
image = "postgres:12"

[services.database.ports]
"5432/tcp" = ""

[services.database.environment]
POSTGRES_USER = "app"
POSTGRES_PASSWORD = "secret"
POSTGRES_DB = "tests"

[services.database.export]
DATABASE_URL = "postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{HOST}:{PORT;5432/tcp}/{POSTGRES_DB}"
