[tests]
min_version = "v0.11.0"
mount = false

[tests.steps]
install = [
    "apt update",
    "apt install nodejs npm",
]

[tests.import]
command = "make -j2 dev"

[tests.ports]
"8000/tcp" = ""
"3000/tcp" = ""

[tests.environment]
TROPHYDICE_APP = "http://{HOST}:{PORT;3000/tcp}/"

[services.redis]
image = "redis:latest"

[services.redis.ports]
"6379/tcp" = ""

[services.redis.export]
REDIS_URL = "redis://{HOST}:{PORT;6379/tcp}"
