[tests]
min_version = "v0.4.0"

[tests.steps]
install = [
    "apt update",
    "apt install nodejs npm",
]

[services.redis]
image = "redis:latest"

[services.redis.ports]
"6379/tcp" = ""

[services.redis.export]
REDIS_URL = "redis://{HOST}:{PORT;6379/tcp}"
